Storm events data from NOAA

In [ ]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
events = pd.read_csv("FloridaJanJuly2025.csv")
events.head()

,EVENT_ID,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EVENT_TYPE,MAGNITUDE,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,...,END_LOCATION,END_DATE,END_TIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EVENT_NARRATIVE,EPISODE_NARRATIVE,ABSOLUTE_ROWNUMBER
0,1226143,BAKER CO.,OLUSTEE,01/18/2025,1719,Heavy Rain,,,0,0,...,OLUSTEE,01/19/2025,519,30.25,-82.42,30.25,-82.42,Mesonet station OLSF1 Olustee measured 12 hr r...,Early morning strong to severe storms formed a...,1
1,1226144,COLUMBIA CO.,WATERTOWN,01/18/2025,1759,Heavy Rain,,,0,0,...,WATERTOWN,01/19/2025,559,30.18,-82.59,30.18,-82.59,Mesonet station TT672 Suwannee Forestry Center...,Early morning strong to severe storms formed a...,2
2,1226145,BAKER CO.,MACCLENNY,01/18/2025,1830,Heavy Rain,,,0,0,...,MACCLENNY,01/19/2025,630,30.27,-82.14,30.27,-82.14,Mesonet station GW1567 MACCLENNY measured rain...,Early morning strong to severe storms formed a...,3
3,1226146,CLAY CO.,HUGH,01/19/2025,0,Heavy Rain,,,0,0,...,HUGH,01/19/2025,636,30.17,-81.99,30.17,-81.99,Site KFLJACKS3741 has had 4.51 inches of | ...,Early morning strong to severe storms formed a...,4
4,1226147,BAKER CO.,MANNING,01/19/2025,0,Heavy Rain,,,0,0,...,MANNING,01/19/2025,642,30.18,-82.25,30.18,-82.25,Site KFLGLENS19 reports 5.03 inches since | ...,Early morning strong to severe storms formed a...,5

In [ ]:

events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 39 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   EVENT_ID             185 non-null    int64
 1   CZ_NAME_STR          185 non-null    object
 2   BEGIN_LOCATION       185 non-null    object
 3   BEGIN_DATE           185 non-null    object
 4   BEGIN_TIME           185 non-null    int64
 5   EVENT_TYPE           185 non-null    object
 6   MAGNITUDE            185 non-null    object
 7   TOR_F_SCALE          185 non-null    object
 8   DEATHS_DIRECT        185 non-null    int64
 9   INJURIES_DIRECT      185 non-null    int64
 10  DAMAGE_PROPERTY_NUM  185 non-null    int64
 11  DAMAGE_CROPS_NUM     185 non-null    int64
 12  STATE_ABBR           185 non-null    object
 13  CZ_TIMEZONE          185 non-null    object
 14  MAGNITUDE_TYPE       185 non-null    object
 15  EPISODE_ID           185 non-null    int64
 16  CZ_TYPE              185 non-null    object
 17  CZ_FIPS              185 non-null    int64
 18  WFO                  185 non-null    object
 19  INJURIES_INDIRECT    185 non-null    int64
 20  DEATHS_INDIRECT      185 non-null    int64
 21  SOURCE               185 non-null    object
 22  FLOOD_CAUSE          185 non-null    object
 23  TOR_LENGTH           185 non-null    object
 24  TOR_WIDTH            185 non-null    object
 25  BEGIN_RANGE          185 non-null    object
 26  BEGIN_AZIMUTH        185 non-null    object
 27  END_RANGE            185 non-null    object
 28  END_AZIMUTH          185 non-null    object
 29  END_LOCATION         185 non-null    object
 30  END_DATE             185 non-null    object
 31  END_TIME             185 non-null    int64
 32  BEGIN_LAT            185 non-null    object
 33  BEGIN_LON            185 non-null    object
 34  END_LAT              185 non-null    object
 35  END_LON              185 non-null    object
 36  EVENT_NARRATIVE      173 non-null    object
 37  EPISODE_NARRATIVE    185 non-null    object
 38  ABSOLUTE_ROWNUMBER   185 non-null    int64
dtypes: int64(12), object(27)
memory usage: 56.5+ KB

In [ ]:
events.describe()

,EVENT_ID,BEGIN_TIME,DEATHS_DIRECT,INJURIES_DIRECT,DAMAGE_PROPERTY_NUM,DAMAGE_CROPS_NUM,EPISODE_ID,CZ_FIPS,INJURIES_INDIRECT,DEATHS_INDIRECT,END_TIME,ABSOLUTE_ROWNUMBER
count,1.850000e+02,185.000000,185.0,185.000000,1.850000e+02,185.000000,185.000000,185.000000,185.000000,185.0,185.000000,185.000000
mean,1.237779e+06,1029.297297,0.0,0.005405,2.381622e+04,48648.648649,199730.697297,74.340541,0.005405,0.0,1281.064865,93.000000
std,8.433474e+03,703.630688,0.0,0.073521,2.868934e+05,148583.203198,1158.711393,62.662985,0.073521,0.0,715.151547,53.549043
min,1.225619e+06,0.000000,0.0,0.000000,0.000000e+00,0.000000,198205.000000,1.000000,0.000000,0.0,0.000000,1.000000
25%,1.231482e+06,455.000000,0.0,0.000000,0.000000e+00,0.000000,198768.000000,31.000000,0.000000,0.0,612.000000,47.000000
50%,1.236801e+06,1134.000000,0.0,0.000000,0.000000e+00,0.000000,199388.000000,69.000000,0.000000,0.0,1238.000000,93.000000
75%,1.244136e+06,1600.000000,0.0,0.000000,0.000000e+00,0.000000,200684.000000,107.000000,0.000000,0.0,1900.000000,139.000000
max,1.258158e+06,2320.000000,0.0,1.000000,3.900000e+06,500000.000000,202375.000000,425.000000,1.000000,0.0,2359.000000,185.000000